name = "chrona-registry"
main = "src/index.ts"
compatibility_date = "2024-09-09"
workers_dev = true

[[kv_namespaces]]
binding = "CHRONA_REGISTRY"
id = "4ef19a82068e42af9b0c66f993999260"

[[routes]]
pattern = "api.chronadocs.xyz/*"
zone_name = "chronadocs.xyz"