packages:
  - packages/*
  - apps/*
minimumReleaseAgeExclude:
  - react-router
  - '@react-router/*'
allowBuilds:
  '@parcel/watcher': false
  '@swc/core': false
  core-js: false
  esbuild: false
  msw: false
  protobufjs: false
  sharp: false
  vue-demi: false
  workerd: true
